###############
# Configuration
###############

uri: /resources/registry/externalServices/paypal/baseUrl
spec:
  value: https://api-m.sandbox.paypal.com
---
uri: /resources/registry/externalServices/paypal/encodedCredentials
spec:
  value: ''
  isSecret: true
